"""Add description and frequency to tasks and is_habit to goals

Revision ID: 034d872406b2
Revises: cbcbbb396535
Create Date: 2025-09-19 12:10:25.040001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '034d872406b2'
down_revision: Union[str, Sequence[str], None] = 'cbcbbb396535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('is_habit', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('repeat_frequency', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'repeat_frequency')
    op.drop_column('tasks', 'description')
    op.drop_column('goals', 'is_habit')
    # ### end Alembic commands ###
