"""Add VIEWED status to PartnerInvitation

Revision ID: 0bab05f3a969
Revises: fd8bf5fa30c1
Create Date: 2025-09-17 18:05:43.321331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bab05f3a969'
down_revision: Union[str, Sequence[str], None] = 'fd8bf5fa30c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
