"""Add last_nudged_at to partner_invitations

Revision ID: 422c73997127
Revises: a015176d7e2c
Create Date: 2025-08-13 20:39:43.599427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422c73997127'
down_revision: Union[str, Sequence[str], None] = 'a015176d7e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_invitations', sa.Column('last_nudged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_invitations', 'last_nudged_at')
    # ### end Alembic commands ###
