"""Add message column to partner_invitations

Revision ID: 424c9e54a463
Revises: 0bab05f3a969
Create Date: 2025-09-18 08:27:55.345643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424c9e54a463'
down_revision: Union[str, Sequence[str], None] = '0bab05f3a969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_invitations', sa.Column('message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_invitations', 'message')
    # ### end Alembic commands ###
