"""Remove rogue foreign key constraint on users.current_partner_id

Revision ID: 74b70e2bafb3
Revises: 625a03cb6b94
Create Date: 2025-07-04 00:38:07.020125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b70e2bafb3'
down_revision: Union[str, Sequence[str], None] = '625a03cb6b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_current_partner_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_current_partner_id_fkey'), 'users', 'partnerships', ['current_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
