"""create_chat_tables

Revision ID: 7641ea5144c7
Revises: f08895c55fc6
Create Date: 2025-09-24 18:12:45.205602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7641ea5144c7'
down_revision: Union[str, Sequence[str], None] = 'f08895c55fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=False),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', name='message_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('reactions',
    sa.Column('reaction_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('attachments')
    op.drop_table('messages')
    # ### end Alembic commands ###
