"""Add is_archived to Goal model

Revision ID: 7e5f0717810e
Revises: 034d872406b2
Create Date: 2025-09-19 20:16:45.062036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5f0717810e'
down_revision: Union[str, Sequence[str], None] = '034d872406b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'is_archived')
    # ### end Alembic commands ###
