"""Create partnership and partner_invitation tables

Revision ID: 92f270af585a
Revises: 
Create Date: 2025-06-27 23:03:03.930190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92f270af585a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('legacy_partnerships')
    # op.add_column('partner_invitations', sa.Column('receiver_id', sa.UUID(), nullable=True))
    op.alter_column('partner_invitations', 'receiver_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('partner_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'accepted', 'rejected', 'revoked', 'expired', name='invitation_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::invitation_status"))
    # op.drop_index(op.f('idx_partner_invitations_receiver_email'), table_name='partner_invitations')
    # op.drop_index(op.f('idx_partner_invitations_sender_id'), table_name='partner_invitations')
    # op.drop_index(op.f('idx_partner_invitations_status'), table_name='partner_invitations')
    # op.create_index(op.f('ix_partner_invitations_receiver_email'), 'partner_invitations', ['receiver_email'], unique=False)
    op.create_foreign_key(None, 'partner_invitations', 'users', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.drop_table_comment(
        'partner_invitations',
        existing_comment='Stores partnership invitations between users',
        schema=None
    )
    # op.drop_constraint(op.f('unique_partnership'), 'partnerships', type_='unique')
    # op.create_unique_constraint('uq_user_partnership', 'partnerships', ['user1_id', 'user2_id'])
    op.drop_table_comment(
        'partnerships',
        existing_comment='Stores active partnerships between users',
        schema=None
    )
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['current_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'partnerships',
        'Stores active partnerships between users',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('uq_user_partnership', 'partnerships', type_='unique')
    op.create_unique_constraint(op.f('unique_partnership'), 'partnerships', ['user1_id', 'user2_id'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'partner_invitations',
        'Stores partnership invitations between users',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'partner_invitations', type_='foreignkey')
    op.drop_index(op.f('ix_partner_invitations_receiver_email'), table_name='partner_invitations')
    op.create_index(op.f('idx_partner_invitations_status'), 'partner_invitations', ['status'], unique=False)
    op.create_index(op.f('idx_partner_invitations_sender_id'), 'partner_invitations', ['sender_id'], unique=False)
    op.create_index(op.f('idx_partner_invitations_receiver_email'), 'partner_invitations', ['receiver_email'], unique=False)
    op.alter_column('partner_invitations', 'status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', 'revoked', 'expired', name='invitation_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::invitation_status"))
    op.alter_column('partner_invitations', 'receiver_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('partner_invitations', 'receiver_id')
    op.create_table('legacy_partnerships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user1_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user2_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inviter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('partnerships_pkey'))
    )
    # ### end Alembic commands ###
