"""Fix User-Partnership foreign key and relationships

Revision ID: a5ffe316ba53
Revises: 92f270af585a
Create Date: 2025-06-28 04:55:38.401325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ffe316ba53'
down_revision: Union[str, Sequence[str], None] = '92f270af585a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_current_partner_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'partnerships', ['current_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_current_partner_id_fkey'), 'users', 'users', ['current_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
