"""Add start_date to Partnership model

Revision ID: db8773867233
Revises: a5ffe316ba53
Create Date: 2025-06-28 15:06:55.756061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8773867233'
down_revision: Union[str, Sequence[str], None] = 'a5ffe316ba53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('partnerships', sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partnerships', 'start_date')
    # ### end Alembic commands ###
