"""Add UserBehavioralMetrics model

Revision ID: f08895c55fc6
Revises: f7bfaab230d2
Create Date: 2025-09-20 13:32:49.938826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08895c55fc6'
down_revision: Union[str, Sequence[str], None] = 'f7bfaab230d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_behavioral_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('time_of_day_success', sa.JSON(), nullable=True),
    sa.Column('procrastination_index', sa.Float(), nullable=True),
    sa.Column('category_affinity', sa.JSON(), nullable=True),
    sa.Column('archetype', sa.String(length=50), nullable=True),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_behavioral_metrics')
    # ### end Alembic commands ###
