"""Add nickname columns to partnership

Revision ID: f51469c8f4f9
Revises: 424c9e54a463
Create Date: 2025-09-18 10:50:07.531663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51469c8f4f9'
down_revision: Union[str, Sequence[str], None] = '424c9e54a463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partnerships', sa.Column('user1_nickname', sa.String(length=100), nullable=True))
    op.add_column('partnerships', sa.Column('user2_nickname', sa.String(length=100), nullable=True))
    op.add_column('partnerships', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('partnerships_user2_id_fkey'), 'partnerships', type_='foreignkey')
    op.create_foreign_key(None, 'partnerships', 'users', ['user2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partnerships', type_='foreignkey')
    op.create_foreign_key(op.f('partnerships_user2_id_fkey'), 'partnerships', 'users', ['user2_id'], ['id'], ondelete='CASCADE')
    op.drop_column('partnerships', 'end_date')
    op.drop_column('partnerships', 'user2_nickname')
    op.drop_column('partnerships', 'user1_nickname')
    # ### end Alembic commands ###
