"""Add preference fields to User model

Revision ID: fd8bf5fa30c1
Revises: 25da6a79d84a
Create Date: 2025-09-17 18:02:30.291572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8bf5fa30c1'
down_revision: Union[str, Sequence[str], None] = '25da6a79d84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_time', sa.String(length=50), server_default='morning', nullable=False))
    op.add_column('users', sa.Column('theme', sa.String(length=50), server_default='system', nullable=False))
    op.add_column('users', sa.Column('privacy_setting', sa.String(length=50), server_default='partner-only', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_setting')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'notification_time')
    # ### end Alembic commands ###
